Loja/Models/Desconto.cs
using System.ComponentModel.DataAnnotations;

namespace Loja.Models
{
    public class Desconto
    {
        public int DescontoId { get; set; }
        public int VendaId { get; set; }
        public Venda? Venda { get; set; }
        [Display(Name = "Valor do Desconto")]
        public decimal ValorDesconto { get; set; }
        public bool Aprovado { get; set; }

    }
}

Loja/Controllers/DescontosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Loja.Data;
using Loja.Models;

namespace Loja.Controllers
{
    public class DescontosController : Controller
    {
        private readonly LojaContext _context;

        public DescontosController(LojaContext context)
        {
            _context = context;

        }
        [AuthorizeRole("Gerente")]
        public IActionResult Desconto()
        {
            return View();
        }

        // GET: Descontos
        /*public async Task<IActionResult> Index()
        {
            var lojaContext = _context.Desconto.Include(d => d.Venda);
            return View(await lojaContext.ToListAsync());
        }*/
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Desconto == null)
            {
                return Problem("Tabela inexistente");
            }
            var descontos = from m in _context.Desconto select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                descontos = descontos.Where(s => s.Venda.BancoFinanciamento!.Contains(searchString));
            }

            return View(await descontos.ToListAsync());
        }

        // GET: Descontos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var desconto = await _context.Desconto
                .Include(d => d.Venda)
                .FirstOrDefaultAsync(m => m.DescontoId == id);
            if (desconto == null)
            {
                return NotFound();
            }

            return View(desconto);
        }

        // GET: Descontos/Create
        public IActionResult Create()
        {
            ViewData["VendaId"] = new SelectList(_context.Set<Venda>(), "VendaId", "VendaId");
            return View();
        }

        // POST: Descontos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DescontoId,VendaId,ValorDesconto,Aprovado")] Desconto desconto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(desconto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["VendaId"] = new SelectList(_context.Set<Venda>(), "VendaId", "VendaId", desconto.VendaId);
            return View(desconto);
        }

        // GET: Descontos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var desconto = await _context.Desconto.FindAsync(id);
            if (desconto == null)
            {
                return NotFound();
            }
            ViewData["VendaId"] = new SelectList(_context.Set<Venda>(), "VendaId", "VendaId", desconto.VendaId);
            return View(desconto);
        }

        // POST: Descontos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DescontoId,VendaId,ValorDesconto,Aprovado")] Desconto desconto)
        {
            if (id != desconto.DescontoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(desconto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DescontoExists(desconto.DescontoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VendaId"] = new SelectList(_context.Set<Venda>(), "VendaId", "VendaId", desconto.VendaId);
            return View(desconto);
        }

        // GET: Descontos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var desconto = await _context.Desconto
                .Include(d => d.Venda)
                .FirstOrDefaultAsync(m => m.DescontoId == id);
            if (desconto == null)
            {
                return NotFound();
            }

            return View(desconto);
        }

        // POST: Descontos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var desconto = await _context.Desconto.FindAsync(id);
            if (desconto != null)
            {
                _context.Desconto.Remove(desconto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DescontoExists(int id)
        {
            return _context.Desconto.Any(e => e.DescontoId == id);
        }
    }
}

Loja/Views/Descontos/Create.cshtml
@model Loja.Models.Desconto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Desconto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="VendaId" class="control-label"></label>
                <select asp-for="VendaId" class ="form-control" asp-items="ViewBag.VendaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ValorDesconto" class="control-label"></label>
                <input asp-for="ValorDesconto" class="form-control" />
                <span asp-validation-for="ValorDesconto" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aprovado" /> @Html.DisplayNameFor(model => model.Aprovado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-sm btn-primary" />
                <a asp-action="Index" class="btn btn-sm btn-warning"> <i class="bi bi-arrow-return-left"></i>Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Loja/Views/Descontos/Delete.cshtml
@model Loja.Models.Desconto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Desconto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venda.VendaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorDesconto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorDesconto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aprovado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aprovado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DescontoId" />
        <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
        <a asp-action="Index" class="btn btn-sm btn-warning"> <i class="bi bi-arrow-return-left"></i>Voltar</a>
    </form>
</div>

Loja/Views/Descontos/Details.cshtml
@model Loja.Models.Desconto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Desconto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venda.VendaId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorDesconto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorDesconto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Aprovado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Aprovado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.DescontoId" class="btn btn-sm btn-info"> <i class="bi bi-journal-text"></i>Editar</a>
    <a asp-action="Index" class="btn btn-sm btn-warning"> <i class="bi bi-arrow-return-left"></i>Voltar</a>
</div>

Loja/Views/Descontos/Edit.cshtml
@model Loja.Models.Desconto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Desconto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DescontoId" />
            <div class="form-group">
                <label asp-for="VendaId" class="control-label"></label>
                <select asp-for="VendaId" class="form-control" asp-items="ViewBag.VendaId"></select>
                <span asp-validation-for="VendaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorDesconto" class="control-label"></label>
                <input asp-for="ValorDesconto" class="form-control" />
                <span asp-validation-for="ValorDesconto" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Aprovado" /> @Html.DisplayNameFor(model => model.Aprovado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-sm btn-primary" />
                <a asp-action="Index" class="btn btn-sm btn-warning"> <i class="bi bi-arrow-return-left"></i>Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Loja/Views/Descontos/Index.cshtml
@model IEnumerable<Loja.Models.Desconto>


@{
    ViewData["Title"] = "Index";
}

<h1>Desconto</h1>

<p>
    <a asp-action="Create" class="btn btn-sm btn-success"> <i class="bi bi-person-plus"></i>Novo Desconto</a>
</p>

<form asp-controller="Descontos" asp-action="Index">
    <p>
        Banco: <input type="text" name="searchString" />
        <input type="submit" value="Filtrar" />
    </p>


</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Venda)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorDesconto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aprovado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Venda.Cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorDesconto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Aprovado)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.DescontoId" class="btn btn-sm btn-info"> <i class="bi bi-journal-text"></i>Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.DescontoId" class="btn btn-sm btn-primary"> <i class="bi bi-pencil"></i>Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.DescontoId" class="btn btn-sm btn-danger"> <i class="bi bi-trash3"></i>Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>