Loja/Models/Carro.cs
using System.ComponentModel.DataAnnotations;

namespace Loja.Models
{
    public class Carro
    {
        public int CarroId { get; set; }
        public string? Modelo { get; set; }
        public string? Marca { get; set; }
        public int Ano { get; set; }
        [Display(Name = "Preço")]
        public decimal Preco { get; set; }
        [Display(Name = "Novo")]
        public bool IsNovo { get; set; }
        public int Estoque { get; set; }
        public string? Url { get; set; }
    }
}

Loja/Controllers/CarrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Loja.Data;
using Loja.Models;

namespace Loja.Controllers
{
    public class CarrosController : Controller
    {
        private readonly LojaContext _context;

        public CarrosController(LojaContext context)
        {
            _context = context;
        }

        // GET: Carros
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Carro == null)
            {
                return Problem("Tabela inexistente");
            }
            var carros = from m in _context.Carro select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                carros = carros.Where(s => s.Marca!.Contains(searchString));
            }

            return View(await carros.ToListAsync());
        }

        // GET: Carros/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carro
                .FirstOrDefaultAsync(m => m.CarroId == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // GET: Carros/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Carros/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarroId,Modelo,Marca,Ano,Preco,IsNovo,Estoque,Url")] Carro carro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carros/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carro.FindAsync(id);
            if (carro == null)
            {
                return NotFound();
            }
            return View(carro);
        }

        // POST: Carros/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarroId,Modelo,Marca,Ano,Preco,IsNovo,Estoque,Url")] Carro carro)
        {
            if (id != carro.CarroId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarroExists(carro.CarroId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carro);
        }

        // GET: Carros/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carro = await _context.Carro
                .FirstOrDefaultAsync(m => m.CarroId == id);
            if (carro == null)
            {
                return NotFound();
            }

            return View(carro);
        }

        // POST: Carros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carro = await _context.Carro.FindAsync(id);
            if (carro != null)
            {
                _context.Carro.Remove(carro);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarroExists(int id)
        {
            return _context.Carro.Any(e => e.CarroId == id);
        }
    }
}

Loja/Views/Carros/Create.cshtml
@model Loja.Models.Carro

@{
    ViewData["Title"] = "Create";
}

<h1>Novo</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsNovo" /> @Html.DisplayNameFor(model => model.IsNovo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Estoque" class="control-label"></label>
                <input asp-for="Estoque" class="form-control" />
                <span asp-validation-for="Estoque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-sm btn-primary" />
                <a asp-action="Index" class="btn btn-sm btn-warning"> <i class="bi bi-arrow-return-left"></i>Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Loja/Views/Carros/Delete.cshtml
@model Loja.Models.Carro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsNovo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsNovo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estoque)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estoque)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CarroId" />
        <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
        <a asp-action="Index" class="btn btn-sm btn-warning"> <i class="bi bi-arrow-return-left"></i>Voltar</a>
    </form>
</div>

Loja/Views/Carros/Details.cshtml
@model Loja.Models.Carro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsNovo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsNovo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estoque)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estoque)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CarroId" class="btn btn-sm btn-info"> <i class="bi bi-journal-text"></i>Editar</a>  
    <a asp-action="Index" class="btn btn-sm btn-warning"> <i class="bi bi-arrow-return-left"></i>Voltar</a>
</div>

Loja/Views/Carros/Edit.cshtml
@model Loja.Models.Carro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CarroId" />
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsNovo" /> @Html.DisplayNameFor(model => model.IsNovo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Estoque" class="control-label"></label>
                <input asp-for="Estoque" class="form-control" />
                <span asp-validation-for="Estoque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-sm btn-primary" />
                <a asp-action="Index" class="btn btn-sm btn-warning"> <i class="bi bi-arrow-return-left"></i>Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Loja/Views/Carros/Index.cshtml
@model IEnumerable<Loja.Models.Carro>

@{
    ViewData["Title"] = "Index";
}

<h1>Carros</h1>

<p>
    <a asp-action="Create" class="btn btn-sm btn-success"> <i class="bi bi-person-plus"></i>Novo Carro</a>
</p>

<form asp-controller="Carros" asp-action="Index">
    <p>
        Marca: <input type="text" name="searchString" />
        <input type="submit" value="Filtrar" />
    </p>


</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsNovo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estoque)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsNovo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estoque)
            </td>
             <td>
                <img src="@Url.Content("~/img/" + @item.Url)" alt="@item.Url" height="100px" />
             </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.CarroId" class="btn btn-sm btn-info"> <i class="bi bi-journal-text"></i>Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.CarroId" class="btn btn-sm btn-primary"> <i class="bi bi-pencil"></i>Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.CarroId" class="btn btn-sm btn-danger"> <i class="bi bi-trash3"></i>Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>